export const cityData={
    1:{name:'New york city',image:'https://source.unsplash.com/SVVTZtTGyaU'},
    2:{name:'London',image:'https://source.unsplash.com/iP8ElEhqHeY'},
    3:{name:'Paris',image:'https://source.unsplash.com/R5scocnOOdM'},
    4:{name:'London',image:'https://source.unsplash.com/Oja2ty_9ZLM'},
    5:{name:'Rome',image:'https://source.unsplash.com/I1Lv2yX67GI'},
    6:{name:'Istanbul',image:'https://source.unsplash.com/0n0AHB1fgTQ'},
    7:{name:'Cairo',image:'https://source.unsplash.com/1Ng-7ESDjvk'},
    8:{name:'Sydney',image:'https://source.unsplash.com/Wp3xWCVXMCI'},
    9:{name:'Dubai',image:'https://source.unsplash.com/q8D7WZc40eA'},
    10:{name:'San francisco',image:'https://source.unsplash.com/AFlG5jpMvYg'},
    11:{name:'tokyo',image:'https://source.unsplash.com/NiyRORf8d8I'},
    12:{name:'Beijing',image:'https://source.unsplash.com/ZwRCXGkv30w'},
    13:{name:'Moscow',image:'https://source.unsplash.com/bPbfaeNpEn4'},
    14:{name:'Rio de Janeiro',image:'https://source.unsplash.com/OkiDIla7K8Q'},
    15:{name:'Mumbai',image:'https://source.unsplash.com/MxabbMSLr_M'},
    16:{name:'Seoul',image:'https://source.unsplash.com/7F65HDP0-E0'},
    17:{name:'Cairo',image:'https://source.unsplash.com/rxv2qwYPe6s'},
    18:{name:'Los Angeles',image:'https://source.unsplash.com/UZVlSjrIJ3o'},
    19:{name:'Berlin',image:'https://source.unsplash.com/pN684G33h_M'},
    20:{name:'Mexico City',image:'https://source.unsplash.com/lDjxXumgpT8'},
    21:{name:'Toronto',image:'https://source.unsplash.com/gOq27RHoL3s'},
    22:{name:'Barcelona',image:'https://source.unsplash.com/WBGjg0DsO_g'},
    23:{name:'Shanghai',image:'https://source.unsplash.com/py8eyAh9J3A'},
    24:{name:'Amsterdam',image:'https://source.unsplash.com/2Hs8zbwOLDA'},
    25:{name:'Bangkok',image:'https://source.unsplash.com/-y3sidWvDxg'},
    26:{name:'Johannesburg',image:'https://source.unsplash.com/_h-L45TSmGM'},
    27:{name:'Singapore',image:'https://source.unsplash.com/sJ7pYyJFyuA'},
    28:{name:'Hong kong',image:'https://source.unsplash.com/4hluhoRJokI'},
    29:{name:'Vancouver',image:'https://source.unsplash.com/2yN10KHNTzM'},
    30:{name:'Chicago',image:'https://source.unsplash.com/b9cRz523N9c'},
    31:{name:'Amsterdam',image:'https://source.unsplash.com/-e4vLFZV9QM'},
    32:{name:'Vienna',image:'https://source.unsplash.com/ZOw0x97sDJg'},
    33:{name:'Dublin',image:'https://source.unsplash.com/KT4dOfvtZSg'},
    34:{name:'Stockholm',image:'https://source.unsplash.com/lqWf-yoQztI'},
    35:{name:'Warsaw',image:'https://source.unsplash.com/p6gxHYb43v0'},
    36:{name:'Cape town',image:'https://source.unsplash.com/1GgWbP74phY'},
    37:{name:'Helsinki',image:'https://source.unsplash.com/bpDJvls-h-0'},
    38:{name:'Oslo',image:'https://source.unsplash.com/f5xUjBgExPg'},
    39:{name:'Karachi',image:'https://source.unsplash.com/ivNmrA2Vg8g'},
    40:{name:'Jakarta',image:'https://source.unsplash.com/mAxA2OmTmKA'},
    41:{name:'Dhaka',image:'https://source.unsplash.com/4SDtJV3RbsI'},
    42:{name:'New Delhi',image:'https://source.unsplash.com/8XZTZIfuNrM'},
    43:{name:'Colombo',image:'https://source.unsplash.com/YZpcMdgnBlA'},
    44:{name:'Sao Saulo',image:'https://source.unsplash.com/9j3qd7gNozs'},
    45:{name:'Wellington',image:'https://source.unsplash.com/9FHO8EssLq0'},
    46:{name:'Auckland',image:'https://source.unsplash.com/x0NvSdPk404'},
    47:{name:'Montreal',image:'https://source.unsplash.com/JJYzJXbwB20'},
    48:{name:'Melbourne',image:'https://source.unsplash.com/-gmtAa0Q5MI'},
    49:{name:'Durban',image:'https://source.unsplash.com/Mx4Lmh7WLGA'},
    50:{name:'Nairobi',image:'https://source.unsplash.com/Zkao_QBEjk8'},
}
