export const cityData={
    1:{name:'new york city',image:'https://source.unsplash.com/SVVTZtTGyaU'},
    2:{name:'london',image:'https://source.unsplash.com/iP8ElEhqHeY'},
    3:{name:'paris',image:'https://source.unsplash.com/R5scocnOOdM'},
    4:{name:'london',image:'https://source.unsplash.com/Oja2ty_9ZLM'},
    5:{name:'rome',image:'https://source.unsplash.com/I1Lv2yX67GI'},
    6:{name:'istanbul',image:'https://source.unsplash.com/0n0AHB1fgTQ'},
    7:{name:'cairo',image:'https://source.unsplash.com/1Ng-7ESDjvk'},
    8:{name:'sydney',image:'https://source.unsplash.com/Wp3xWCVXMCI'},
    9:{name:'dubai',image:'https://source.unsplash.com/q8D7WZc40eA'},
    10:{name:'san francisco',image:'https://source.unsplash.com/AFlG5jpMvYg'},
    11:{name:'tokyo',image:'https://source.unsplash.com/NiyRORf8d8I'},
    12:{name:'Beijing',image:'https://source.unsplash.com/ZwRCXGkv30w'},
    13:{name:'Moscow',image:'https://source.unsplash.com/bPbfaeNpEn4'},
    14:{name:'Rio de Janeiro',image:'https://source.unsplash.com/OkiDIla7K8Q'},
    15:{name:'Mumbai',image:'https://source.unsplash.com/MxabbMSLr_M'},
    16:{name:'Seoul',image:'https://source.unsplash.com/7F65HDP0-E0'},
    17:{name:'Cairo',image:'https://source.unsplash.com/rxv2qwYPe6s'},
    18:{name:'Los Angeles',image:'https://source.unsplash.com/UZVlSjrIJ3o'},
    19:{name:'Berlin',image:'https://source.unsplash.com/pN684G33h_M'},
    20:{name:'Mexico City',image:'https://source.unsplash.com/lDjxXumgpT8'},
    21:{name:'toronto',image:'https://source.unsplash.com/gOq27RHoL3s'},
    22:{name:'Barcelona',image:'https://source.unsplash.com/WBGjg0DsO_g'},
    23:{name:'Shanghai',image:'https://source.unsplash.com/py8eyAh9J3A'},
    24:{name:'Amsterdam',image:'https://source.unsplash.com/2Hs8zbwOLDA'},
    25:{name:'bangkok',image:'https://source.unsplash.com/-y3sidWvDxg'},
    26:{name:'johannesburg',image:'https://source.unsplash.com/_h-L45TSmGM'},
    27:{name:'singapore',image:'https://source.unsplash.com/sJ7pYyJFyuA'},
    28:{name:'hong kong',image:'https://source.unsplash.com/4hluhoRJokI'},
    29:{name:'vancouver',image:'https://source.unsplash.com/2yN10KHNTzM'},
    30:{name:'chicago',image:'https://source.unsplash.com/b9cRz523N9c'},
    31:{name:'amsterdam',image:'https://source.unsplash.com/-e4vLFZV9QM'},
    32:{name:'vienna',image:'https://source.unsplash.com/ZOw0x97sDJg'},
    33:{name:'dublin',image:'https://source.unsplash.com/KT4dOfvtZSg'},
    34:{name:'stockholm',image:'https://source.unsplash.com/lqWf-yoQztI'},
    35:{name:'warsaw',image:'https://source.unsplash.com/p6gxHYb43v0'},
    36:{name:'cape town',image:'https://source.unsplash.com/1GgWbP74phY'},
    37:{name:'helsinki',image:'https://source.unsplash.com/bpDJvls-h-0'},
    38:{name:'oslo',image:'https://source.unsplash.com/f5xUjBgExPg'},
    39:{name:'karachi',image:'https://source.unsplash.com/ivNmrA2Vg8g'},
    40:{name:'jakarta',image:'https://source.unsplash.com/mAxA2OmTmKA'},
    41:{name:'dhaka',image:'https://source.unsplash.com/4SDtJV3RbsI'},
    42:{name:'new delhi',image:'https://source.unsplash.com/8XZTZIfuNrM'},
    43:{name:'colombo',image:'https://source.unsplash.com/YZpcMdgnBlA'},
    44:{name:'sao paulo',image:'https://source.unsplash.com/9j3qd7gNozs'},
    45:{name:'wellington',image:'https://source.unsplash.com/9FHO8EssLq0'},
    46:{name:'auckland',image:'https://source.unsplash.com/x0NvSdPk404'},
    47:{name:'montreal',image:'https://source.unsplash.com/JJYzJXbwB20'},
    48:{name:'melbourne',image:'https://source.unsplash.com/-gmtAa0Q5MI'},
    49:{name:'durban',image:'https://source.unsplash.com/Mx4Lmh7WLGA'},
    50:{name:'nairobi',image:'https://source.unsplash.com/Zkao_QBEjk8'},
}
