export const cityData={
    1:{name:'Great wall of china',image:'https://source.unsplash.com/HwY9R6_YzgM'},
    2:{name:'Great wall of china',image:'https://source.unsplash.com/hB_nkwIw5f4'},
    3:{name:'Taj Mahal',image:'https://source.unsplash.com/5l56DRqrpEI'},
    4:{name:'Taj Mahal',image:'https://source.unsplash.com/_WuPjE-MPHo'},
    5:{name:'Eiffel Tower',image:'https://source.unsplash.com/QAwciFlS1g4'},
    6:{name:'Eiffel Tower',image:'https://source.unsplash.com/-7XJZ4tHBZQ'},
    7:{name:'Statue of Liberty',image:'https://source.unsplash.com/vdjLv8Gwo0g'},
    8:{name:'Statue of Liberty',image:'https://source.unsplash.com/i1Yt31-Onuo'},
    9:{name:'Machu Picchu',image:'https://source.unsplash.com/KOICsAuhoc4'},
    10:{name:'Machu Picchu',image:'https://source.unsplash.com/VddWWTaTnpQ'},
    11:{name:'Pyramids of Giza',image:'https://source.unsplash.com/CJ4mbwSK3EY'},
    12:{name:'Pyramids of Giza',image:'https://source.unsplash.com/hAw4e-F4klY'},
    13:{name:'Colosseum',image:'https://source.unsplash.com/zDTLfEZHL14'},
    14:{name:'Colosseum',image:'https://source.unsplash.com/rDB0GUsvjKc'},
    15:{name:'Big Ben',image:'https://source.unsplash.com/iXqTqC-f6jI'},
    16:{name:'Big Ben',image:'https://source.unsplash.com/BUYyLzxI56k'},
    17:{name:'Grand Canyon',image:'https://source.unsplash.com/ZLxUbNoDYUw'},
    18:{name:'Grand Canyon',image:'https://source.unsplash.com/XuQGqCBpNGk'},
    19:{name:'Mount Everest',image:'https://source.unsplash.com/oBX-b6ltYts'},
    20:{name:'Mount Everest',image:'https://source.unsplash.com/XEW_Wd4240c'},
    21:{name:'Burj Khalifa',image:'https://source.unsplash.com/XqeELkkUDSQ'},
    22:{name:'Burj Khalifa',image:'https://source.unsplash.com/NUIiWNLxmSc'},
    23:{name:'Mount Fuji',image:'https://source.unsplash.com/MdXvFqH6y-k'},
    24:{name:'Mount Fuji',image:'https://source.unsplash.com/dvifDfIB3W0'},
    25:{name:'Golden Gate Bridge',image:'https://source.unsplash.com/gZXx8lKAb7Y'},
    26:{name:'Golden Gate Bridge',image:'https://source.unsplash.com/L0n-HJaeTXM'},
    27:{name:'Petra',image:'https://source.unsplash.com/mYEqvgcY1G4'},
    28:{name:'Petra',image:'https://source.unsplash.com/B6kxDMIP8xg'},
    29:{name:'Mount Rushmore',image:'https://source.unsplash.com/wcbgvxloc6Q'},
    30:{name:'Mount Rushmore',image:'https://source.unsplash.com/J3xqZx3ELJc'},
    31:{name:'Tokyo Tower',image:'https://source.unsplash.com/81qWYgmIV_A'},
    32:{name:'Tokyo Tower',image:'https://source.unsplash.com/esk8zPwPY'},
    33:{name:'Niagara Falls',image:'https://source.unsplash.com/rSVYDPtMTRE'},
    34:{name:'Niagara Falls',image:'https://source.unsplash.com/OZ-PaZPVl6c'},
    35:{name:'Qutub Minar',image:'https://source.unsplash.com/wmuXzoLk'},
    36:{name:'Qutub Minar',image:'https://source.unsplash.com/BavOi6bbT9U'},
    37:{name:'Gateway of India',image:'https://source.unsplash.com/F8hOsdh93Rc'},
    38:{name:'Gateway of India',image:'https://source.unsplash.com/v4tYukU-N70'},
    39:{name:'Great Sphinx of Giza',image:'https://source.unsplash.com/JIRsG1pmA7U'},
    40:{name:'Great Sphinx of Giza',image:'https://source.unsplash.com/xL5d-lPQyaY'},
    41:{name:'Edinburgh Castle',image:'https://source.unsplash.com/LCOT2KY0hQo'},
    42:{name:'Edinburgh Castle',image:'https://source.unsplash.com/S56zN8cV5fk'},
    43:{name:'Statue Christ the Redeemer',image:'https://source.unsplash.com/vEQe_DuVmKk'},
    44:{name:'Statue Christ the Redeemer',image:'https://source.unsplash.com/N73S2OUozl0'},
    45:{name:'Golden Temple',image:'https://source.unsplash.com/JDrNTJk8u0s'},
    46:{name:'Golden Temple',image:'https://source.unsplash.com/Oen3x_COL2U'},
    47:{name:'Hawa Mahal',image:'https://source.unsplash.com/To6i1FNfsOc'},
    48:{name:'Hawa Mahal',image:'https://source.unsplash.com/ZN6D_iZOfPk'},
    49:{name:'millennium park',image:'https://source.unsplash.com/kouAo3VSP6g'},
    50:{name:'millennium park',image:'https://source.unsplash.com/43gH8RJdaqk'},
}
